//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InternetoweBazyDanych.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wypozyczenia
    {
        public int idWypozyczenia { get; set; }
        public System.DateTime terminWypozyczenia { get; set; }
        public System.DateTime terminZwrotu { get; set; }
        public Nullable<int> idUzytkownika { get; set; }
        public Nullable<int> idStatusu { get; set; }
        public Nullable<int> idKsiazki { get; set; }
    
        public virtual Ksiazki Ksiazki { get; set; }
        public virtual Statusy_Wypozyczen Statusy_Wypozyczen { get; set; }
        public virtual Uzytkownicy Uzytkownicy { get; set; }
    }
}
